Jobs opening in AddWebSolution
GDGAhmedabad/devfestahm pull request #129
Opened 2022-12-09 12:25 UTC by Pooja-addweb

2022-12-09 18:44 UTC, JaldeepAsodariya requested changes

2022-12-09 18:44 UTC, JaldeepAsodariya commented on public/data/job-openings-data.json
> +        {
Please apply Format Document

2022-12-11 04:19 UTC, JaldeepAsodariya commented
@Pooja-addweb  Can you please check the requested changes?
Thanks

2022-12-12 05:08 UTC, Pooja-addweb commented
Sure, I am checking it.

Thanks & Regards,
[image: Logo] <https://www.addwebsolution.com/> [image: Logo]
Pooja Upadhyay
People Operations Manager
[image: Skype icon] hr.addweb | www.addwebsolution.com
07929705640
*Socialize with us on*
[image: Facebook icon]
<https://www.facebook.com/addwebsolution.pvt.ltd> [image:
LinkedIn icon] <https://www.linkedin.com/company/addwebsolution> [image:
Twitter icon] <https://twitter.com/addwebsolution> [image: Youtbue icon]
<https://www.youtube.com/channel/UCtZHMXcJ8lLW-ikFNKOszlQ> [image: Youtbue
icon] <https://tinyurl.com/y3hjg25j>



On Sun, Dec 11, 2022 at 9:49 AM Jaldeep Asodariya ***@***.***>
wrote:

> @Pooja-addweb <https://github.com/Pooja-addweb> Can you please check the
> requested changes?
> Thanks
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GDGAhmedabad/devfestahm/pull/129#issuecomment-1345453150>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH4XGDMH3VPEHVJAQQBDBRLWMVI4DANCNFSM6AAAAAASZJG4WE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-12 05:25 UTC, Pooja-addweb commented
Hello Team,

Required changes are done.

Thanks & Regards,
[image: Logo] <https://www.addwebsolution.com/> [image: Logo]
Pooja Upadhyay
People Operations Manager
[image: Skype icon] hr.addweb | www.addwebsolution.com
07929705640
*Socialize with us on*
[image: Facebook icon]
<https://www.facebook.com/addwebsolution.pvt.ltd> [image:
LinkedIn icon] <https://www.linkedin.com/company/addwebsolution> [image:
Twitter icon] <https://twitter.com/addwebsolution> [image: Youtbue icon]
<https://www.youtube.com/channel/UCtZHMXcJ8lLW-ikFNKOszlQ> [image: Youtbue
icon] <https://tinyurl.com/y3hjg25j>



On Mon, Dec 12, 2022 at 10:38 AM Pooja Upadhyay ***@***.***>
wrote:

> Sure, I am checking it.
>
> Thanks & Regards,
> [image: Logo] <https://www.addwebsolution.com/> [image: Logo]
> Pooja Upadhyay
> People Operations Manager
> [image: Skype icon] hr.addweb | www.addwebsolution.com
> 07929705640
> *Socialize with us on*
> [image: Facebook icon] <https://www.facebook.com/addwebsolution.pvt.ltd> [image:
> LinkedIn icon] <https://www.linkedin.com/company/addwebsolution> [image:
> Twitter icon] <https://twitter.com/addwebsolution> [image: Youtbue icon]
> <https://www.youtube.com/channel/UCtZHMXcJ8lLW-ikFNKOszlQ> [image:
> Youtbue icon] <https://tinyurl.com/y3hjg25j>
>
>
>
> On Sun, Dec 11, 2022 at 9:49 AM Jaldeep Asodariya <
> ***@***.***> wrote:
>
>> @Pooja-addweb <https://github.com/Pooja-addweb> Can you please check the
>> requested changes?
>> Thanks
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/GDGAhmedabad/devfestahm/pull/129#issuecomment-1345453150>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AH4XGDMH3VPEHVJAQQBDBRLWMVI4DANCNFSM6AAAAAASZJG4WE>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-12-12 10:00 UTC, JaldeepAsodariya approved these changes

2022-12-12 10:01 UTC, merged

2022-12-12 10:05 UTC, Pooja-addweb commented
Hello,

Kindly inform me when I can see my Job live on the site ?.

Thanks & Regards,
[image: Logo] <https://www.addwebsolution.com/> [image: Logo]
Pooja Upadhyay
People Operations Manager
[image: Skype icon] hr.addweb | www.addwebsolution.com
07929705640
*Socialize with us on*
[image: Facebook icon]
<https://www.facebook.com/addwebsolution.pvt.ltd> [image:
LinkedIn icon] <https://www.linkedin.com/company/addwebsolution> [image:
Twitter icon] <https://twitter.com/addwebsolution> [image: Youtbue icon]
<https://www.youtube.com/channel/UCtZHMXcJ8lLW-ikFNKOszlQ> [image: Youtbue
icon] <https://tinyurl.com/y3hjg25j>



On Mon, Dec 12, 2022 at 3:31 PM Jaldeep Asodariya ***@***.***>
wrote:

> Merged #129 <https://github.com/GDGAhmedabad/devfestahm/pull/129> into
> develop.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GDGAhmedabad/devfestahm/pull/129#event-8012363120>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH4XGDONLFDTFK6EQ2VLBZ3WM3ZWPANCNFSM6AAAAAASZJG4WE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-13 05:57 UTC, JaldeepAsodariya commented
@Pooja-addweb It's live now, Please check over the official website.
Thank you