Feature iview job post
GDGAhmedabad/devfestahm pull request #130
Opened 2022-12-09 12:30 UTC by Bhavisha-iView

2022-12-09 12:33 UTC, PareshMayani commented
@Bhavisha-iView thank you for sending a PR. Could you please either Rebase or send a fresh PR with only your commits?

2022-12-09 12:38 UTC, PareshMayani commented
> @Bhavisha-iView thank you for sending a PR. Could you please either Rebase or send a fresh PR with only your commits? Also, you need to send a PR to `develop` branch

@Bhavisha-iView I've changed the Base to `develop` branch. I would request you to verify your PR changes once and confirm.

2022-12-09 12:52 UTC, Bhavisha-iView commented
> > @Bhavisha-iView thank you for sending a PR. Could you please either Rebase or send a fresh PR with only your commits? Also, you need to send a PR to `develop` branch
> 
> @Bhavisha-iView I've changed the Base to `develop` branch. I would request you to verify your PR changes once and confirm.

@PareshMayani I have verified changes, thanks.

2022-12-09 18:47 UTC, JaldeepAsodariya requested changes

2022-12-09 18:47 UTC, JaldeepAsodariya commented on public/data/job-openings-data.json
> +      "companyLogoUrl": "https://drive.google.com/file/d/1uMPCQCefDW97WQa22a0Gtj03lZrOqLL1/view?usp=share_link",
This URL will not work (Company logo will not load), Please refer other jobs object.

2022-12-11 04:18 UTC, JaldeepAsodariya commented
@Bhavisha-iView Can you please check the requested changes?
Thanks

2022-12-12 10:02 UTC, merged